// Code generated by kun; DO NOT EDIT.
// github.com/RussellLuo/kun

package api

import (
	"context"

	"github.com/RussellLuo/kun/pkg/httpoption"
	"github.com/RussellLuo/validating/v3"
	"github.com/go-kit/kit/endpoint"
)

type DeleteTaskRequest struct {
	Name string `json:"-"`
}

// ValidateDeleteTaskRequest creates a validator for DeleteTaskRequest.
func ValidateDeleteTaskRequest(newSchema func(*DeleteTaskRequest) validating.Schema) httpoption.Validator {
	return httpoption.FuncValidator(func(value interface{}) error {
		req := value.(*DeleteTaskRequest)
		return httpoption.Validate(newSchema(req))
	})
}

type DeleteTaskResponse struct {
	Err error `json:"-"`
}

func (r *DeleteTaskResponse) Body() interface{} { return r }

// Failed implements endpoint.Failer.
func (r *DeleteTaskResponse) Failed() error { return r.Err }

// MakeEndpointOfDeleteTask creates the endpoint for s.DeleteTask.
func MakeEndpointOfDeleteTask(s Service) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req := request.(*DeleteTaskRequest)
		err := s.DeleteTask(
			ctx,
			req.Name,
		)
		return &DeleteTaskResponse{
			Err: err,
		}, nil
	}
}

type ExecuteRequest struct {
	Name  string         `json:"name"`
	Input map[string]any `json:"input"`
}

// ValidateExecuteRequest creates a validator for ExecuteRequest.
func ValidateExecuteRequest(newSchema func(*ExecuteRequest) validating.Schema) httpoption.Validator {
	return httpoption.FuncValidator(func(value interface{}) error {
		req := value.(*ExecuteRequest)
		return httpoption.Validate(newSchema(req))
	})
}

type ExecuteResponse struct {
	Output map[string]any `json:"output"`
	Err    error          `json:"-"`
}

func (r *ExecuteResponse) Body() interface{} { return &r.Output }

// Failed implements endpoint.Failer.
func (r *ExecuteResponse) Failed() error { return r.Err }

// MakeEndpointOfExecute creates the endpoint for s.Execute.
func MakeEndpointOfExecute(s Service) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req := request.(*ExecuteRequest)
		output, err := s.Execute(
			ctx,
			req.Name,
			req.Input,
		)
		return &ExecuteResponse{
			Output: output,
			Err:    err,
		}, nil
	}
}

type GetTaskRequest struct {
	Name string `json:"-"`
}

// ValidateGetTaskRequest creates a validator for GetTaskRequest.
func ValidateGetTaskRequest(newSchema func(*GetTaskRequest) validating.Schema) httpoption.Validator {
	return httpoption.FuncValidator(func(value interface{}) error {
		req := value.(*GetTaskRequest)
		return httpoption.Validate(newSchema(req))
	})
}

type GetTaskResponse struct {
	Definition map[string]any `json:"definition"`
	Err        error          `json:"-"`
}

func (r *GetTaskResponse) Body() interface{} { return r }

// Failed implements endpoint.Failer.
func (r *GetTaskResponse) Failed() error { return r.Err }

// MakeEndpointOfGetTask creates the endpoint for s.GetTask.
func MakeEndpointOfGetTask(s Service) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req := request.(*GetTaskRequest)
		definition, err := s.GetTask(
			ctx,
			req.Name,
		)
		return &GetTaskResponse{
			Definition: definition,
			Err:        err,
		}, nil
	}
}

type UpsertTaskRequest struct {
	Name       string         `json:"-"`
	Definition map[string]any `json:"definition"`
}

// ValidateUpsertTaskRequest creates a validator for UpsertTaskRequest.
func ValidateUpsertTaskRequest(newSchema func(*UpsertTaskRequest) validating.Schema) httpoption.Validator {
	return httpoption.FuncValidator(func(value interface{}) error {
		req := value.(*UpsertTaskRequest)
		return httpoption.Validate(newSchema(req))
	})
}

type UpsertTaskResponse struct {
	Err error `json:"-"`
}

func (r *UpsertTaskResponse) Body() interface{} { return r }

// Failed implements endpoint.Failer.
func (r *UpsertTaskResponse) Failed() error { return r.Err }

// MakeEndpointOfUpsertTask creates the endpoint for s.UpsertTask.
func MakeEndpointOfUpsertTask(s Service) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req := request.(*UpsertTaskRequest)
		err := s.UpsertTask(
			ctx,
			req.Name,
			req.Definition,
		)
		return &UpsertTaskResponse{
			Err: err,
		}, nil
	}
}
