// Code generated by kun; DO NOT EDIT.
// github.com/RussellLuo/kun

package api

import (
	"reflect"

	"github.com/RussellLuo/kun/pkg/oas2"
)

var (
	base = `swagger: "2.0"
info:
  title: "No Title"
  version: "0.0.0"
  description: ""
  license:
    name: "MIT"
host: "example.com"
basePath: "/"
schemes:
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"
`

	paths = `
paths:
  /tasks/{name}:
    delete:
      description: ""
      summary: ""
      operationId: "DeleteTask"
      parameters:
        - name: name
          in: path
          required: true
          type: string
          description: ""
        - name: Authorization
          in: header
          required: true
          type: string
          description: ""
      %s
    get:
      description: ""
      summary: ""
      operationId: "GetTask"
      parameters:
        - name: name
          in: path
          required: true
          type: string
          description: ""
        - name: Authorization
          in: header
          required: true
          type: string
          description: ""
      %s
    put:
      description: ""
      summary: ""
      operationId: "UpsertTask"
      parameters:
        - name: name
          in: path
          required: true
          type: string
          description: ""
        - name: Authorization
          in: header
          required: true
          type: string
          description: ""
        - name: body
          in: body
          schema:
            $ref: "#/definitions/UpsertTaskRequestBody"
      %s
  /:
    post:
      description: ""
      summary: ""
      operationId: "Execute"
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: ""
        - name: body
          in: body
          schema:
            $ref: "#/definitions/ExecuteRequestBody"
      %s
`
)

func getResponses(schema oas2.Schema) []oas2.OASResponses {
	return []oas2.OASResponses{
		oas2.GetOASResponses(schema, "DeleteTask", 200, &DeleteTaskResponse{}),
		oas2.GetOASResponses(schema, "GetTask", 200, &GetTaskResponse{}),
		oas2.GetOASResponses(schema, "UpsertTask", 200, &UpsertTaskResponse{}),
		oas2.GetOASResponses(schema, "Execute", 200, &ExecuteResponse{}),
	}
}

func getDefinitions(schema oas2.Schema) map[string]oas2.Definition {
	defs := make(map[string]oas2.Definition)

	oas2.AddResponseDefinitions(defs, schema, "DeleteTask", 200, (&DeleteTaskResponse{}).Body())

	oas2.AddDefinition(defs, "ExecuteRequestBody", reflect.ValueOf(&struct {
		Name  string         `json:"name"`
		Input map[string]any `json:"input"`
	}{}))
	oas2.AddResponseDefinitions(defs, schema, "Execute", 200, (&ExecuteResponse{}).Body())

	oas2.AddResponseDefinitions(defs, schema, "GetTask", 200, (&GetTaskResponse{}).Body())

	oas2.AddDefinition(defs, "UpsertTaskRequestBody", reflect.ValueOf(&struct {
		Definition map[string]any `json:"definition"`
	}{}))
	oas2.AddResponseDefinitions(defs, schema, "UpsertTask", 200, (&UpsertTaskResponse{}).Body())

	return defs
}

func OASv2APIDoc(schema oas2.Schema) string {
	resps := getResponses(schema)
	paths := oas2.GenPaths(resps, paths)

	defs := getDefinitions(schema)
	definitions := oas2.GenDefinitions(defs)

	return base + paths + definitions
}
